#!/bin/sh

set -e

lb config noauto \
        --distribution bookworm \
	--archive-areas "main contrib non-free" \
	--updates false \
        --security false \
	--backports false \
	--debian-installer live \
	--debian-installer-gui false \
        --iso-volume UFlinux \
	--binary-images iso-hybrid \
	--iso-application "UFlinux Live" \
	--iso-preparer "UFlinux" \
	--iso-publisher "UFlinux" \
	--linux-flavours "x64v1-xanmod1" \
	--linux-packages "linux-image-6.0.10" \
	--chroot-squashfs-compression-level 19 \
	--chroot-squashfs-compression-type zstd \
	--compression gzip \
	--apt-indices false \
	--checksums sha1 \
	--architectures amd64 \
	--clean \
	--win32-loader false \
	--bootappend-live "boot=live components locales=en_US.UTF-8 apparmor=1 security=apparmor psi=1 quiet splash fbcon=nodefer vt.global_cursor_default=0 hostname=uflinux-live username=live-user" \
